"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ # Import the django-environ library to load environment files.
import os # Import the standard operating system tool to work with directories.
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR represents the main folder of our Django backend.
BASE_DIR = Path(__file__).resolve().parent.parent

# 1. Initialize our environment reading tool.
# We create an instance of the environment reader. We can set defaults, like forcing
# DEBUG to be False if it is not explicitly configured in the .env file (for safety!).
env = environ.Env(
    DEBUG=(bool, False)
)

# 2. Tell Django where the 'private drawer' (.env file) is.
# We look inside the BASE_DIR (our main backend folder) for a file named '.env'.
# If the file exists, this utility reads all of its variables into memory.
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# 3. Pull our secret keys and modes from the env variables.
# This prevents our sensitive security credentials from being hardcoded in the file.
SECRET_KEY = env('SECRET_KEY')

# We check if we are in learning/testing mode (True) or production mode (False).
DEBUG = env('DEBUG')

# ALLOWED_HOSTS is read as a list of strings from the comma-separated .env variable.
# This lists the address of the computers that are allowed to run our server.
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


# Application definition
# This is a list of all active tools and packages in our Django server.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # We add the CORS headers package so Django knows how to append permission headers.
    'corsheaders',
]

# The Middleware acts like a series of security bouncers standing in a hallway.
# When a browser request enters, it walks through each bouncer in order from top to bottom.
MIDDLEWARE = [
    # The CORS bouncer MUST stand right at the front door to check origins immediately!
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# We load our database setup from the env file. Using 'env.db' parses the complex connection
# string in DATABASE_URL (like sqlite:///db.sqlite3) and turns it into Django's configuration.
DATABASES = {
    'default': env.db('DATABASE_URL', default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ==============================================================================
# SECURITY, CORS & CSRF CONFIGURATIONS (Bouncer Rules)
# ==============================================================================

# 1. CORS Allowed Origins:
# This tells our Django server which website domains are allowed to send requests.
# We pull this comma-separated list directly from our .env file.
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=['http://localhost:3000'])

# 2. CORS Allow Credentials:
# This is crucial! It tells Django to allow the browser to send security credentials,
# like our secure HttpOnly login session cookies, back and forth across different ports.
CORS_ALLOW_CREDENTIALS = True

# 3. CSRF Trusted Origins:
# CSRF (Cross-Site Request Forgery) is a security feature that stops hackers from
# making requests on your behalf. In modern Django, if your client app runs on a 
# different port, you MUST explicitly tell Django to trust that client origin.
CSRF_TRUSTED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=['http://localhost:3000'])
